<Project>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup Condition="'$(CreateOSPackageVersion)' == ''">
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\src\CreateOS.Sandbox\CreateOS.Sandbox.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(CreateOSPackageVersion)' != ''">
    <PackageReference Include="CreateOS.Sandbox" Version="$(CreateOSPackageVersion)" />
  </ItemGroup>
</Project>
